### ISSUE TITLE
Enumerate clipboard formats on clipboard?

### ISSUE THREAD

**Issue by PeterPanino** [ddablib/cbview#1]
Today, what is the most reliable way to get all CLIPBOARD FORMATS available on the clipboard?

In "Clipboard Format Spy" (2014), you wrote: "I think it's safe to say that the code base is stale." [sic]

**Comment by delphidabbler** [comment]
The best way I guess, would be to find some platform independent way of doing it. Since I only write for Windows I've never investigated the matter. A place to start with a modern delphi maybe to dig into the platform agnostic parts of the RTL.

For Windows, the last time I investigated a few years back, I think the approach was interface based. From what little I remember you could get objects from Windows that used the same interfaces as in drag & drop - `IDataObject` springs to mind.

But I'm afraid that's all I can recall. One of the reasons I archived [Clipboard Format Spy](https://github.com/delphidabbler/cfs) is that I didn't have time to learn how to modernise it!  I suggest a search on MSDN for `IDataObject` may the way to get started.
